---
title: "FPR project"
author: "Krista DeStasio & Brendan Cullen"
date: "4/15/2019"
output: html_document
---

```{r setup, include=FALSE}
library("factoextra")
library("tidyverse")
library("janitor")
library("here")

knitr::opts_chunk$set(echo = TRUE)
```

Info about the data set is [available on Kaggle](https://www.kaggle.com/rounakbanik/pokemon), as is the data itself.  
```{r}
pokemon <- clean_names(read.csv("pokemon.csv"))
#iris_clean <- clean_names(iris)

pokemon_type <- pokemon %>% 
    select(., -percentage_male) %>% 
    drop_na() %>% 
    .["type1"]

pokemon_data <- pokemon %>% 
    select_if(is.numeric) %>% 
    select(., -percentage_male) %>% 
    drop_na()

pokemon_scaled <- scale(pokemon_data)

clust_out <- eclust(pokemon_data, 
                     FUNcluster = 'kmeans', 
                     hc_metric = 'euclidean',
                     k = 3, nstart = 25, graph = FALSE)
 
# str(clust_out)
# mclust::clPairs(pokemon_data, clust_out$cluster)

cluster <- clust_out$cluster
clust_data <- cbind( cluster, pokemon_type, pokemon_data)

fviz_silhouette(clust_out, palette = "jco",
                         print.summary = FALSE) + 
             theme_minimal() + 
             ggtitle(paste0("Silhouette Plot of K-means With ", 3, " Clusters"))

sil <- clust_out$silinfo$widths[, 1:3]
neg_sil_index <- which(sil[, 'sil_width'] < 0)





plot_data <- clust_data %>% 
    mutate(cluster = as.character(cluster), pokemon_type = as.character(pokemon_type)) %>% 
    gather(., value = value, key = variable_name, -pokemon_type, -cluster) 

plot_data$cluster <- as_factor(plot_data$cluster)
plot_data$pokemon_type <- as_factor(plot_data$pokemon_type)

plot_data %>% 
    ggplot(aes(x = variable_name, y = value, color = cluster)) +
    geom_jitter()
    
plot_data %>% 
    ggplot(aes(x = variable_name, y = value, color = cluster)) +
    geom_jitter() + 
    facet_wrap(~pokemon_type)


```

