---
title: "Outline"
author: "Brendan Cullen & Krista DeStasio"
date: "5/1/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(janitor) 
library(tidyverse)
library(factoextra)
library(RColorBrewer)
knitr::opts_chunk$set(echo = TRUE)
```

# Set-up
```{r Import and clean data}
# Read in the data
pokemon_data <- clean_names(read.csv("pokemon.csv"))

# Code the data types appropriately
vars <- c("is_legendary", "generation", "pokedex_number") 
pokemon_data[vars] <- lapply(pokemon_data[vars], factor) 

# Create a data frame without missing values that contains the type1 labels
pokemon_data <- pokemon_data %>% 
    select(-percentage_male, -type2) %>%  
    filter(type1 %in% c("ghost", "fairy", "dragon")) %>%  # Let's limit this to a few pokemon
    mutate(type1 = droplevels(type1)) %>% # Few poke have data for these
    drop_na() 

# Drop any non-numeric variables
pokemon_numeric <- pokemon_data %>% 
    select_if(is.numeric) %>%  
    as.data.frame(.)

# Create data frame with "against" variables 
pokemon_against <- pokemon_numeric %>% 
    select(starts_with("against"), hp)

# Create data frame with all other variables
pokemon_other <- pokemon_numeric %>% 
    select(-starts_with("against"))
pokemon_datacamp <- pokemon_numeric %>% 
    select(hp, attack, defense, sp_attack, sp_defense)
```

# Preprocessing
```{r Missing observations}
table(is.na(pokemon_data)) # we good
```


```{r Outliers}

```


```{r, Zero and near-zero variance}
#caret::nearZeroVar(pokemon_numeric, saveMetrics = TRUE) # we good
```


```{r Multicolinearity.}
#caret::findLinearCombos(pokemon_numeric) 

# Remove speed since it is a linear combination of other variables
pokemon_numeric <- dplyr::select(pokemon_numeric, -speed)
```


```{r Data scaling}
pokemon_numeric <- pokemon_numeric %>% 
    scale() %>% 
    as.data.frame(.)

pokemon_other <- pokemon_other %>% 
    scale() %>% 
    as.data.frame(.)

pokemon_datacamp <- pokemon_datacamp %>% 
    scale() %>% 
    as.data.frame(.)

pokemon_against <- pokemon_against %>% 
    scale() %>% 
    as.data.frame(.)
# Check the scaling
#round(colMeans(pokemon_numeric), 2)
#apply(pokemon_numeric, 2, sd)
```

```{r PCA}
# pokemon_scaled_pca <- prcomp(x = pokemon_numeric)
# 
# biplot(pokemon_scaled_pca)
# 
# pca_summary_pokemon <- summary(pokemon_scaled_pca)
# 
# knitr::kable(pca_summary_pokemon$importance, digits = 2, 
#       caption = 'PCA Summary Table, Pokemon Dataset')
```


# Run K-means clustering with variable numbers of clusters

```{r}
run_clust <- function(df, k) {
    eclust(df,
           FUNcluster = 'kmeans',
           hc_metric = 'euclidean',
           k = k, nstart = 25, graph = TRUE)
}
```

Test, run with 
```{r}
set.seed(4966)
#rownames(pokemon_numeric) <- c()

pokemon_datacamp_km <- run_clust(pokemon_datacamp, 3)
pokemon_against_km <- run_clust(pokemon_against, 3)
pokemon_other_km <- run_clust(pokemon_other, 3)
```

```{r}
set.seed(4966)
# Make silplot
fviz_silhouette(pokemon_datacamp_km, palette = "jco", 
                print.summary = FALSE, 
                ggtheme = theme_minimal()) 
fviz_silhouette(pokemon_against_km, palette = "jco", 
                print.summary = FALSE, 
                ggtheme = theme_minimal()) 
fviz_silhouette(pokemon_other_km, palette = "jco", 
                print.summary = FALSE, 
                ggtheme = theme_minimal())

## datacamp variables
plot_data <- cbind(pokemon_datacamp_km$cluster, pokemon_data) %>%  
    mutate(cluster = as.character(pokemon_datacamp_km$cluster), pokemon_type = as.character(type1)) %>% 
    gather(., value = value, key = variable_name, -pokemon_type, -cluster) 

plot_data$cluster <- as_factor(plot_data$cluster)
plot_data$pokemon_type <- as_factor(plot_data$pokemon_type)

plot_data %>% 
    ggplot(aes(x = variable_name, y = value, color = cluster)) +
    geom_jitter() + 
    facet_wrap(~pokemon_type)

# "Against" variables
plot_data <- cbind(pokemon_against_km$cluster, pokemon_against, pokemon_data$type1) %>%  
  rename(cluster = `pokemon_against_km$cluster`,
         type = `pokemon_data$type1`) %>% 
    mutate(cluster = as.character(cluster), 
           type = as.character(type)) %>% 
    gather(value = value, key = variable_name, -type, -cluster) 

plot_data$cluster <- as_factor(plot_data$cluster)
plot_data$pokemon_type <- as_factor(plot_data$pokemon_type)

plot_data %>% 
    ggplot(aes(x = variable_name, y = value, color = cluster)) +
    geom_jitter(alpha = 0.3) + 
  coord_flip() +
    facet_wrap(~type) +
  theme_minimal()

## Other (non-against) variables
plot_data <- cbind(pokemon_other_km$cluster, pokemon_data) %>%  
    mutate(cluster = as.character(pokemon_other_km$cluster), pokemon_type = as.character(type1)) %>% 
    gather(., value = value, key = variable_name, -pokemon_type, -cluster) 

plot_data$cluster <- as_factor(plot_data$cluster)
plot_data$pokemon_type <- as_factor(plot_data$pokemon_type)

plot_data %>% 
    ggplot(aes(x = variable_name, y = value, color = cluster)) +
    geom_jitter() + 
    facet_wrap(~pokemon_type)

# Plot average silhouette plot
fviz_nbclust(pokemon_datacamp, kmeans, method = "silhouette", k.max = 32) + theme_classic()
fviz_nbclust(pokemon_against, kmeans, method = "silhouette", k.max = 40) + theme_classic()
fviz_nbclust(pokemon_other, kmeans, method = "silhouette", k.max = 32) + theme_classic()
```

```{r}

```

# Visualizations

```{r Scatterplot or Biplot}
scat_plot <- function(cluster_data, plot_data) {
    nclusts <- max(unique(cluster_data$cluster))
    plot(plot_data, 
         col = cluster_data$cluster, 
         main = paste(nclusts, "clusters:", deparse(substitute(cluster_data))))
}
```

Test it
```{r Boxplots}

```


```{r Sillouhette Plots}
fviz_silhouette(pokemon_kmeans, palette = "jco", 
                print.summary = FALSE, 
                ggtheme = theme_minimal())
```


```{r SPLOM plots}

```


```{r Tables}
# Centroid value (mean of cluster; `centers` from kmeans output)
# Within-cluster sum of squares for each cluster (`withinss` from the kmeans output)
# Number of observations per cluster (`size` from kmeans output)

```

